# netlify.toml - Configuration file for Netlify deployment

[build]
  publish = "dist"
  command = "npm run build"

# This ensures all routes work with a single-page application (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200