import "./index.css";
import {
  StreamRoom,
  WalletAdapterBridge,
  VidbloqProvider,
  BaseCallControls,
  MicrophoneControl,
  CameraControl,
  ScreenShareControl,
  RecordControl,
  MediaControls,
  StreamView,
  AudioTrack,
  VideoTrack,
  // CallControls,
  // UserView,
  // Prejoin,
  // ParticipantView,
  // ParticipantControls,
  // ReactionsBar,
} from "./components/index";

import {
  checkParticipantMicEnabled,
  checkIfLocalParticipant,
  getAvatarUrl,
  getParticipantMetadata,
  getUserName,
  getUserType,
  isMobileDevice,
  getTokenBalance,
} from "./utils/index";

import { ShareModal } from "./components/ui-remove/modals";

import {
  useTransaction,
  useVidbloqProgram,
  useParticipantList,
  useDownloadParticipants,
  useStreamContext,
  useWalletContext,
  useRequirePublicKey,
  usePrejoin,
  useCreateStream,
  useTenantContext,
  useWebSocket,
  // useLivestream,
  // useMeeting,
  useNotification,
  useStreamAddons,
  useCallReactions,
  useCreateAgenda,
  useHandleStreamDisconnect,
  useGetStreamAgenda,
  useDeleteAgenda,
  useUpdateStreamAgenda,
  useGetAgenda,
  useGetQuizQuestions,
  useGetQuizResults,
  useGetUserQuizAnswers,
  useSubmitQuizAnswers,
  useSubmitPollVote,
  useGetPollResults,
  useGetUserPollVote,
  useStreamRecordingYoutube,
  useParticipantControls,
  useParticipantData,
  useStreamRoom,
  useCustomChat as useChat,
  useIsLocalParticipant,
  useLocalParticipant,
  useParticipantNotifications,
  useContest,
} from "./hooks/index";

import {
  SDKTrackSource,
  SDKTrackKind,
  SDKParticipant,
  SDKTrackReference,
  SDKTrackPublication,
  SDKChatMessage,
  SDKRoom,
  ParticipantMetadata,
  Agenda,
  AddonType,
  ParticipantSortStrategy,
  Participant,
  CallControlsRenderProps,
} from "./types";

export {
  StreamRoom,
  WalletAdapterBridge,
  VidbloqProvider,
  BaseCallControls,
  // UserView,
  // Prejoin,
  // CallControls,
  // ReactionsBar,
  // useLivestream,
  // useMeeting,
  // ParticipantView,
  // ParticipantControls,
  MicrophoneControl,
  CameraControl,
  ScreenShareControl,
  RecordControl,
  MediaControls,
  StreamView,
  useTransaction,
  useVidbloqProgram,
  useParticipantList,
  useDownloadParticipants,
  useStreamContext,
  useWalletContext,
  useRequirePublicKey,
  usePrejoin,
  useCreateStream,
  useTenantContext,
  useWebSocket,
  useNotification,
  useStreamAddons,
  useCallReactions,
  useCreateAgenda,
  useHandleStreamDisconnect,
  useGetUserQuizAnswers,
  useSubmitQuizAnswers,
  useGetStreamAgenda,
  useDeleteAgenda,
  useUpdateStreamAgenda,
  useGetAgenda,
  useGetQuizQuestions,
  useGetQuizResults,
  useSubmitPollVote,
  useGetPollResults,
  useGetUserPollVote,
  useStreamRecordingYoutube,
  useParticipantControls,
  useParticipantData,
  useStreamRoom,
  useChat,
  useContest,
  useIsLocalParticipant,
  useLocalParticipant,
  useParticipantNotifications,
  checkParticipantMicEnabled,
  checkIfLocalParticipant,
  isMobileDevice,
  getTokenBalance,
  SDKTrackSource,
  SDKTrackKind,
  VideoTrack,
  AudioTrack,
  getUserType,
  getUserName,
  getAvatarUrl,
  getParticipantMetadata,
  ParticipantSortStrategy,
};

export type {
  SDKParticipant,
  SDKTrackReference,
  SDKTrackPublication,
  SDKChatMessage,
  SDKRoom,
  ParticipantMetadata,
  Agenda,
  AddonType,
  CallControlsRenderProps,
  Participant,
};

export { ShareModal };
