import "./index.css";
import {
  StreamRoom,
  WalletAdapterBridge,
  VidbloqProvider,
  BaseCallControls,
  UserView,
  Prejoin,
  MicrophoneControl,
  CameraControl,
  ScreenShareControl,
  CallControls,
  RecordControl,
  MediaControls,
  StreamView,
  ParticipantView,
  ParticipantControls,
  AudioTrack,
  VideoTrack,
  ReactionsBar,
} from "./components/index";

import {
  checkParticipantMicEnabled,
  checkIfLocalParticipant,
  getAvatarUrl,
  getParticipantMetadata,
  getUserName,
  getUserType,
} from "./utils/index";

import {
  useTransaction,
  useVidbloqProgram,
  useParticipantList,
  useStreamContext,
  useWalletContext,
  useRequirePublicKey,
  usePrejoin,
  useCreateStream,
  useTenantContext,
  useWebSocket,
  useLivestream,
  useMeeting,
  useNotification,
  useStreamAddons,
  useCallReactions,
  useCreateAgenda,
  useHandleStreamDisconnect,
  useGetStreamAgenda,
  useDeleteAgenda,
  useUpdateStreamAgenda,
  useGetQuizQuestions,
  useGetQuizResults,
  useGetUserQuizAnswers,
  useSubmitQuizAnswers,
} from "./hooks/index";

import {
  SDKTrackSource,
  SDKTrackKind,
  SDKParticipant,
  SDKTrackReference,
  SDKTrackPublication,
  SDKRoom,
  ParticipantMetadata,
  Agenda,
  AddonType,
} from "./types";

export {
  StreamRoom,
  WalletAdapterBridge,
  VidbloqProvider,
  BaseCallControls,
  UserView,
  Prejoin,
  MicrophoneControl,
  CameraControl,
  ScreenShareControl,
  RecordControl,
  MediaControls,
  CallControls,
  ReactionsBar,
  StreamView,
  useTransaction,
  useVidbloqProgram,
  useParticipantList,
  useStreamContext,
  useWalletContext,
  useRequirePublicKey,
  usePrejoin,
  useCreateStream,
  useTenantContext,
  useWebSocket,
  useLivestream,
  useMeeting,
  useNotification,
  useStreamAddons,
  useCallReactions,
  useCreateAgenda,
  useHandleStreamDisconnect,
  useGetUserQuizAnswers,
  useSubmitQuizAnswers,
  useGetStreamAgenda,
  useDeleteAgenda,
  useUpdateStreamAgenda,
  useGetQuizQuestions,
  useGetQuizResults,
  checkParticipantMicEnabled,
  checkIfLocalParticipant,
  ParticipantView,
  ParticipantControls,
  SDKTrackSource,
  SDKTrackKind,
  VideoTrack,
  AudioTrack,
  getUserType,
  getUserName,
  getAvatarUrl,
  getParticipantMetadata,
};

export type {
  SDKParticipant,
  SDKTrackReference,
  SDKTrackPublication,
  SDKRoom,
  ParticipantMetadata,
  Agenda,
  AddonType,
};
